spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boottest04
    username: root
    password: root
    #    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081
#驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      jing:
        mapper: debug
---
spring:
  redis:
    host: 192.168.19.128